### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DougTy** [DougTy/dino-graph#1]
- [x] Redo hover display
	- [x] Show multiple line values
	- [x] If not hovered, show latest values
	- [x] Display as line down Y axis instead of point
	- [x] Interpolate values between points
	- [x] Better positioning
- [x] Split mode
	- [x] Make dataPadding add space to the center in split mode
	- [x] Negative Y axis labels
	- [x] Negative grid lines
	- [x] Fix peaks going off-screen with centerPadding > 0
- [x] Fix top label getting cut off
- [x] Option to draw points
- [x] Option to draw ONLY points (scatter plot)
- [x] lineColours as a function
- [x] Only call render() when necessary (mouseover or data is updated)
- [x] mouseIn and mouseOut -- only do mouse stuff when mouse is in
- [x] Update batching
	- [x] updateLock on setData
	- [x] manualUpdates option for using setLineData
- [x] Rename & document all config options
- [x] X axis labels
- [x] Render to internal canvas -- drawImage, slider & values to real canvas
- [x] Add options for all remaining statically defined values (colours, etc...)
- [x] Separate options for X and Y labels & grid
- [x] X axis grid
- [x] Viewport options
	- [x] Zooming
	- [x] Clamp start and end region values to edges of data area (when mouse goes offscreen)
	- [x] Make sense of what's happening when you zoom into a dynamically updated graph
	- [x] Fix zoom bar offset when minX > 0
	- [x] Cancel if selection is too small (and/or when dataAtPos returns false?)
	- [x] Panning
		- [x] Abstract zoom bar bounds into a function (x, y, w, h)
	- [x] Clamp bar to edges instead of returning out
	- [x] Lock updates while panning
	- [x] Pan steps (move in increments so it doesn't fully update every mouse pixel of movement)
	- [x] Maintain unzoomed maxY while zoomed?
	- [x] Maximum x value range (max zoom out, default zoom in)
	- [x] Attach right-most scroll to maxX while updating
	- [x] Move zoom notice to top right
	- [x] Update docs with new options
- [x] Bypass shadeColour if string isn't hex
- [x] Update readme, package.json, & make a better demo w/ zoom
- [ ] Remove top offset from clipping so peak points are fully visible
- [ ] Attempt to use Object.keys to turn x:y: objects into array on setData
- [ ] Attempt to use interpolated values to stack between missing X values
- [x] Add dinosaur
