### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DougTy** [DougTy/dino-graph#1]
- [ ] Redo hover display
	- [ ] Show multiple line values
	- [ ] If not hovered, show latest values
	- [ ] Display as line down Y axis instead of point
	- [ ] Interpolate values between points?
	- [ ] Sync hovered line/X value between all charts?
- [ ] Split mode
	- [ ] Does not work when maxV is automatically calculated
	- [ ] Need dynamic dataPadding as a separate value calculated by negative peaks
	- [ ] Negative Y axis labels
- [ ] X axis labels
- [ ] Use Object.keys to turn x:y: objects into array on setData
- [ ] getYOffset function for canvasHeight - dataPadding - splitOffset
- [ ] Viewport options
	- [ ] Panning & zooming
	- [ ] Restrict maximum X value range, scroll right if it goes past
- [ ] lineColours as a function
- [ ] Document all config options
